name: Check
on: [pull_request]

jobs:
  tsc:
    name: Svelte Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: pnpm run check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: pnpm exec prettier --check .

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - run: pnpm exec eslint .

  commitlint:
    name: CommitLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/setup
      - if: github.event_name == 'push'
        run: pnpm commitlint -- --last --verbose
      - if: github.event_name == 'pull_request'
        run: pnpm commitlint -- --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
